### ISSUE TITLE
Settings not available in command palette

### ISSUE THREAD

**Issue by vivekpayasi** [material-theme/vsc-material-theme-icons#112]
I installed the Material Theme Icons extension (but not Material Theme) and enabled one of the icon themes (Light). Icons have also updated on the sidebar. But I can't find any settings in the command palette as mentioned in the `README.md`. (screenshot below)

<img width="664" alt="Screen Shot 2019-12-31 at 12 00 39" src="https://user-images.githubusercontent.com/9135530/71612339-cad91f00-2bc5-11ea-94d6-78b8fdeb9a55.png">

Perhaps, it is not adding in the settings.

**Comment by LasaleFamine** [comment]
Hi @vivekpayasi, thanks for using our icons. 

Actually this is an expected behaviour: we don't instantiate this setting from the icons if you don't have Material Theme installed, this because both things are strictly correlated, you can only change the accent from the Material Theme and then update the icons to reflect that change. 

If you want to change the accent of your icons based on the accent set on the Material Theme you should install the theme before.
